
services:
  backend:
    build:
      context: .
      dockerfile: Project-2.API/Dockerfile
    ports:
      - "5236:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

  frontend:
    build:
      context: ./JAZA-FRONT
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
