name: Build and Push Frontend and Backend to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Project-2.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jaza-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./JAZA-FRONT
          file: ./JAZA-FRONT/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jaza-frontend:latest
